# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: 1BitUral add-on
version: "1.0.0"
slug: 1BitUral
description: 1BitUral add-on
url: "https://github.com/dubovcev/addons-ha_bitural/tree/main/ha_bitural"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-ha_bitural"
